    [deploy]
bucket = 'artifacts-cfn'
region = 'ap-south-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'aws-project-cruddur'
ArtifactBucketName = "codepipeline-cruddur-artifacts"
BuildSpec = 'backend-flask/buildspec.yml'